import type { Flight } from './types';

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: '1',
    airline: 'SkyWings',
    flightNumber: 'SW101',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '08:00',
    arrivalTime: '11:30',
    durationMinutes: 210,
    stops: 0,
    price: 350,
    currency: 'USD'
  },
  {
    id: '2',
    airline: 'BlueAir',
    flightNumber: 'BA202',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '10:00',
    arrivalTime: '14:45',
    durationMinutes: 285,
    stops: 1,
    price: 280,
    currency: 'USD'
  },
  {
    id: '3',
    airline: 'OceanJet',
    flightNumber: 'OJ303',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '12:00',
    arrivalTime: '15:15',
    durationMinutes: 195,
    stops: 0,
    price: 420,
    currency: 'USD'
  },
  {
    id: '4',
    airline: 'SkyWings',
    flightNumber: 'SW105',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '14:00',
    arrivalTime: '17:45',
    durationMinutes: 225,
    stops: 0,
    price: 380,
    currency: 'USD'
  },
  {
    id: '5',
    airline: 'BlueAir',
    flightNumber: 'BA208',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '16:00',
    arrivalTime: '22:30',
    durationMinutes: 390,
    stops: 2,
    price: 220,
    currency: 'USD'
  },
  {
    id: '6',
    airline: 'GlobalAirlines',
    flightNumber: 'GA404',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '06:30',
    arrivalTime: '09:50',
    durationMinutes: 200,
    stops: 0,
    price: 390,
    currency: 'USD'
  },
  {
    id: '7',
    airline: 'OceanJet',
    flightNumber: 'OJ310',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '09:15',
    arrivalTime: '12:35',
    durationMinutes: 200,
    stops: 0,
    price: 360,
    currency: 'USD'
  },
  {
    id: '8',
    airline: 'GlobalAirlines',
    flightNumber: 'GA412',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '11:45',
    arrivalTime: '16:20',
    durationMinutes: 275,
    stops: 1,
    price: 295,
    currency: 'USD'
  },
  {
    id: '9',
    airline: 'SkyWings',
    flightNumber: 'SW115',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '18:00',
    arrivalTime: '21:15',
    durationMinutes: 195,
    stops: 0,
    price: 410,
    currency: 'USD'
  },
  {
    id: '10',
    airline: 'BlueAir',
    flightNumber: 'BA218',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '19:30',
    arrivalTime: '23:55',
    durationMinutes: 265,
    stops: 1,
    price: 275,
    currency: 'USD'
  },
  {
    id: '11',
    airline: 'OceanJet',
    flightNumber: 'OJ320',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '05:00',
    arrivalTime: '08:15',
    durationMinutes: 195,
    stops: 0,
    price: 340,
    currency: 'USD'
  },
  {
    id: '12',
    airline: 'GlobalAirlines',
    flightNumber: 'GA425',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '07:45',
    arrivalTime: '11:05',
    durationMinutes: 200,
    stops: 0,
    price: 370,
    currency: 'USD'
  },
  {
    id: '13',
    airline: 'SkyWings',
    flightNumber: 'SW125',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '13:30',
    arrivalTime: '16:45',
    durationMinutes: 195,
    stops: 0,
    price: 400,
    currency: 'USD'
  },
  {
    id: '14',
    airline: 'BlueAir',
    flightNumber: 'BA230',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '15:15',
    arrivalTime: '20:00',
    durationMinutes: 285,
    stops: 1,
    price: 260,
    currency: 'USD'
  },
  {
    id: '15',
    airline: 'OceanJet',
    flightNumber: 'OJ335',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '20:00',
    arrivalTime: '23:15',
    durationMinutes: 195,
    stops: 0,
    price: 430,
    currency: 'USD'
  },
  {
    id: '16',
    airline: 'GlobalAirlines',
    flightNumber: 'GA440',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '22:00',
    arrivalTime: '01:15',
    durationMinutes: 195,
    stops: 0,
    price: 330,
    currency: 'USD'
  },
  {
    id: '17',
    airline: 'SkyWings',
    flightNumber: 'SW140',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '00:30',
    arrivalTime: '03:45',
    durationMinutes: 195,
    stops: 0,
    price: 310,
    currency: 'USD'
  },
  {
    id: '18',
    airline: 'BlueAir',
    flightNumber: 'BA245',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '03:00',
    arrivalTime: '07:35',
    durationMinutes: 275,
    stops: 1,
    price: 250,
    currency: 'USD'
  },
  {
    id: '19',
    airline: 'OceanJet',
    flightNumber: 'OJ350',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '17:00',
    arrivalTime: '21:20',
    durationMinutes: 260,
    stops: 1,
    price: 300,
    currency: 'USD'
  },
  {
    id: '20',
    airline: 'GlobalAirlines',
    flightNumber: 'GA455',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '09:00',
    arrivalTime: '13:40',
    durationMinutes: 280,
    stops: 1,
    price: 285,
    currency: 'USD'
  },
  {
    id: '21',
    airline: 'SkyWings',
    flightNumber: 'SW155',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '21:00',
    arrivalTime: '00:15',
    durationMinutes: 195,
    stops: 0,
    price: 440,
    currency: 'USD'
  },
  {
    id: '22',
    airline: 'BlueAir',
    flightNumber: 'BA260',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '11:00',
    arrivalTime: '16:30',
    durationMinutes: 330,
    stops: 2,
    price: 210,
    currency: 'USD'
  },
  {
    id: '23',
    airline: 'OceanJet',
    flightNumber: 'OJ365',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '14:30',
    arrivalTime: '17:45',
    durationMinutes: 195,
    stops: 0,
    price: 375,
    currency: 'USD'
  },
  {
    id: '24',
    airline: 'GlobalAirlines',
    flightNumber: 'GA470',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '05:45',
    arrivalTime: '09:05',
    durationMinutes: 200,
    stops: 0,
    price: 355,
    currency: 'USD'
  },
  {
    id: '25',
    airline: 'SkyWings',
    flightNumber: 'SW170',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '10:30',
    arrivalTime: '13:45',
    durationMinutes: 195,
    stops: 0,
    price: 395,
    currency: 'USD'
  },
  {
    id: '26',
    airline: 'BlueAir',
    flightNumber: 'BA275',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '18:45',
    arrivalTime: '23:20',
    durationMinutes: 275,
    stops: 1,
    price: 265,
    currency: 'USD'
  },
  {
    id: '27',
    airline: 'OceanJet',
    flightNumber: 'OJ380',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '01:00',
    arrivalTime: '04:15',
    durationMinutes: 195,
    stops: 0,
    price: 320,
    currency: 'USD'
  },
  {
    id: '28',
    airline: 'GlobalAirlines',
    flightNumber: 'GA485',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '16:30',
    arrivalTime: '19:45',
    durationMinutes: 195,
    stops: 0,
    price: 385,
    currency: 'USD'
  },
  {
    id: '29',
    airline: 'SkyWings',
    flightNumber: 'SW185',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '23:00',
    arrivalTime: '02:15',
    durationMinutes: 195,
    stops: 0,
    price: 305,
    currency: 'USD'
  },
  {
    id: '30',
    airline: 'BlueAir',
    flightNumber: 'BA290',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '07:00',
    arrivalTime: '11:40',
    durationMinutes: 280,
    stops: 1,
    price: 270,
    currency: 'USD'
  },
  {
    id: '31',
    airline: 'OceanJet',
    flightNumber: 'OJ395',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '12:45',
    arrivalTime: '16:00',
    durationMinutes: 195,
    stops: 0,
    price: 405,
    currency: 'USD'
  }
];
